- name: my-playbook
  hosts: server
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update
      apt:
          upgrade: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: no

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: no

    - name: Install Docker Module for Python
      pip:
        name:
            - docker
            - docker-compose
    - name: Change permissions of /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Create /etc/phat directory
      file:
        path: /home/ubuntu/ansible
        state: directory

    - name: Copy docker-compose.yml file to remote machine
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/ansible/docker-compose.yml

    - name: Deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /home/ubuntu/ansible
        files:
          - docker-compose.yml
        state: present

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
